### ISSUE TITLE
[Back] 회원가입 플로우 변경

### ISSUE THREAD

**Issue by Bellroute** [sproutt/eussya-eussya-api#123]
[참고] https://www.postype.com/

**Comment by wijehyeon** [comment]
@Bellroute 저 사이트처럼 인증없이 회원가입처리만 하면 됩니까? ㅋㅋㅋ

**Comment by hyukjin-lee** [comment]
지금 으쌰으쌰 회원가입 절차가 회원가입 정보 채우기 -> 이메일 인증 -> 회원가입 완료인데,
https://github.com/sproutt/eussya-eussya-view/issues/94 이러한 논의가 이뤄졌었고
몇번의 의논 끝에 회원가입 후 이메일 인증을 별도로 하는걸로 구현하기로 했습니다.
기존에 가입과 인증이 하나로 구현된걸 분리시켜주시면 될 것 같습니다.
