### ISSUE TITLE
[DISCUSS]

### ISSUE THREAD

**Issue by wijehyeon** [sproutt/eussya-eussya-api#133]
- 문제
채팅기능 카프카로구현하려고 하는데 어떨까

- 나의 생각
공부할겸 좋은듯

- 질문
https://github.com/sproutt/eussya-eussya-api/discussions/132

**Comment by wijehyeon** [comment]
채팅기능은
1차로 WS/ STOMP
2차로 부가기능 or 기능보완을 위한 기술 search/adopt 방향으로 진행하겠습니다

**Comment by Bellroute** [comment]
인력 필요하면 말씀해주세요!
