### ISSUE TITLE
회원 가입 api 내부 로직 분리

### ISSUE THREAD

**Issue by Bellroute** [sproutt/eussya-eussya-api#54]
- 현재 회원가입 api를 요청하면 서비스단에서 회원 생성과 동시에 메일을 전송하도록 구현되어 있음.
- 하나의 기능에서 두 가지 일을 동시에 하고 있음

회원 생성과 메일 전송을 분리시켜서 클라이언트에서 요청을 두 번 하는 방식으로 변경하면 어떨까요?

회원 가입 요청 -> 회원 생성 -> 회원 생성 성공 응답 -> 메일 인증 코드 전송 요청 -> 인증 코드 전송 -> 인증 코드 전송 성공 응답

**Comment by hyukjin-lee** [comment]
서비스 로직은 하나의 트랜잭션으로 묶여야하느냐 에 대해서 생각해보면 좋을 것 같아요.
회원가입은 성공했는데 메일 보내는 과정에서 에러가 발생했을 경우? 트랜잭션이 분리되어있으면 롤백 하는 것이 어려울 것으로 보입니다. 디비에는 있는데 메일은 안보내진.. 그런 상태가 되겠죠?
이 관점에서 같이 고민해보면 좋을 것 같습니다
