### ISSUE TITLE
회원 엔티티에 들어가야할 정보

### ISSUE THREAD

**Issue by Bellroute** [sproutt/eussya-eussya-api#6]
Member

memberId
password
nickname
profileImage

의견 부탁드립니다

**Comment by GiPyoo** [comment]
제가 잘은 모르지만 OAuth 관련 정보가 들어가야할 것 같습니다. OAuth로 회원가입을 하는 방식이기 때문입니다.

**Comment by hyukjin-lee** [comment]
현재 기본적으로만 필요한 것은 위 정보와, email 정보, phonenumber 정도 있으면 될 것 같습니다.
oauth 를 한다고 해도, 기본 회원가입은 디폴트로 필요하니까요
