### ISSUE TITLE
[요청] 서버 타임존 포맷

### ISSUE THREAD

**Issue by GiPyoo** [sproutt/eussya-eussya-api#76]
- 메인화면을 만드는 입장에서 화면에 시간을 표기할 때 서버 시간을 따라야합니다. 때문에 두 가지 방법이 존재합니다.
1. 서버의 타임존을 받아와 설정하고 서버시간을 표시한다.
2. 매초 서버에 요청한다.
3. 서버시간은 Asia/Seoul로 고정한다.

1번의 경우에는 한번의 요청으로 시간을 표기할 수 있는데, 이러한 시간 표기를 하기위해서는 javascript의 moment 라이브러리를 사용해야합니다. 이 때, moment 의 tz 함수는 [이 링크](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)의 TZ databasename 이 필요합니다. 
2번의 경우 너무 많은 리소스를 처리하는 것 같습니다.
3번은 고정된 타임존을 클라이언트에서 적용하여 보여주는 방법입니다. 

어떤 방법이 좋을지 질문합니다. 만약 1번의 경우로 한다면 해당 데티터를 넘겨 받을 수 있는지 궁금합니다.

참고자료
https://meetup.toast.com/posts/125
https://meetup.toast.com/posts/130
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by Bellroute** [comment]
1번이 좋은 것 같습니다. 그리고 프론트에서 클라의 현재 위치를 넘길 수 있다면 지역별 시간대도 맞춰서 넘길 수 있을 것 같습니다! 데이터는 클라에서 원하는 포맷으로 넘길 수 있을 것 같습니다.
아니면 응답 헤더에 Date로 GMT 시간대로 현재 시간이 넘어오는데 그거 사용하면 어떤가요?
