### ISSUE TITLE
[Back] 로그인 요청 시 토큰 전달 문제

### ISSUE THREAD

**Issue by Bellroute** [sproutt/eussya-eussya-api#88]
로그인 요청에 대한 응답으로 토큰을 헤더로 전송하고 있음
-> 보안 이슈로 클라이언트에서 해당 응답 헤더에 접근할 수 없음
-> 응답 body로 토큰 전달하도록 코드 수정 필요

**Comment by GiPyoo** [comment]
관련 링크 https://stackoverflow.com/a/52921407
